"use client";

import React, { useState } from "react";

const navItems = [
  { label: "Home", href: "/" },
  { label: "How it works", href: "/#how-it-works" },
  { label: "Features", href: "/#features" },
  { label: "About", href: "/#about" },
  { label: "Contact", href: "/#contact" },
];

const definitions = [
  {
    term: "Cookie",
    desc: "A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you, such as your language preference or login details.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
  },
  {
    term: "Company",
    desc: 'When this policy mentions "Company," "we," "us," or "our," it refers to Bar Huddle Corporation (29 Hillside Road, Greenwich, CT 06830), which is responsible for your information under this Privacy Policy.',
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5m0 0v-5a2 2 0 012-2h2a2 2 0 012 2v5m-6 0h6" />
      </svg>
    ),
  },
  {
    term: "Country",
    desc: "Refers to the country where Bar Huddle and its owners or founders are based, which in this case is the United States.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 002 2h1.5a2.5 2.5 0 002.5-2.5V11a2 2 0 012-2h1.055" />
      </svg>
    ),
  },
  {
    term: "Customer",
    desc: "Refers to the company, organization, or person that signs up to use the Bar Huddle Service to manage relationships with its consumers or service users.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
      </svg>
    ),
  },
  {
    term: "Device",
    desc: "Any internet-connected device, such as a phone, tablet, computer, or any other device, that can be used to access Bar Huddle and its services.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 18h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
      </svg>
    ),
  },
  {
    term: "IP Address",
    desc: "A unique number assigned to every device connected to the internet. Usually assigned in geographic blocks, an IP address can often be used to identify the location from which a device connects.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
      </svg>
    ),
  },
  {
    term: "Personnel",
    desc: "Refers to individuals who are employed by Bar Huddle or are under contract to perform services on behalf of one of the parties.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
      </svg>
    ),
  },
  {
    term: "Personal Data",
    desc: "Any information that, directly, indirectly, or in connection with other information (including a personal identification number), allows for the identification or identifiability of a natural person.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
      </svg>
    ),
  },
  {
    term: "Service",
    desc: "Refers to the service provided by Bar Huddle as described in the relevant terms (where applicable) and on this platform.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
      </svg>
    ),
  },
  {
    term: "Third-Party Service",
    desc: "Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we believe may interest you.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
      </svg>
    ),
  },
  {
    term: "You",
    desc: "A person or entity that is registered with Bar Huddle to use the Services.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
  },
];

const tocSections = [
  { id: "intro", label: "Introduction" },
  { id: "definitions", label: "Definitions & Key Terms" },
  { id: "info-collected", label: "Information We Collect" },
  { id: "third-party-end-user", label: "End User Info from 3rd Parties" },
  { id: "third-party-customer", label: "Customer Info from 3rd Parties" },
  { id: "sharing-info", label: "Sharing Information" },
  { id: "collection-scope", label: "Where & When Info is Collected" },
  { id: "use-info", label: "How We Use Information" },
  { id: "email-usage", label: "How We Use Email Addresses" },
  { id: "retention", label: "Information Retention" },
  { id: "protection", label: "How We Protect Your Info" },
  { id: "international-transfers", label: "Cross-Border Transfers" },
  { id: "security-standards", label: "Security & Safeguards" },
  { id: "update-correct", label: "Updating & Correcting Info" },
  { id: "personnel", label: "Personnel Data" },
  { id: "business-sale", label: "Sale of Business" },
  { id: "affiliates", label: "Affiliates" },
  { id: "governing-law", label: "Governing Law & Consent" },
  { id: "user-consent", label: "Your Consent" },
  { id: "external-links", label: "Links to Other Websites" },
  { id: "cookies", label: "Cookies" },
  { id: "blocking-cookies", label: "Blocking & Disabling Cookies" },
  { id: "kids-privacy", label: "Kids' Privacy" },
  { id: "policy-changes", label: "Changes to Privacy Policy" },
  { id: "third-party-services", label: "Third-Party Services" },
  { id: "tracking-tech", label: "Tracking Technologies" },
  { id: "gdpr-compliance", label: "GDPR Compliance" },
  { id: "california-ccpa", label: "California Residents (CCPA)" },
  { id: "caloppa", label: "CalOPPA Rights" },
  { id: "contact-us", label: "Contact Us" },
];

const storeButtons = [
  {
    eyebrow: "Available on the",
    label: "App Store",
    icon: "/figmaAssets/logos-apple-app-store.svg",
    iconClass: "w-[22px] h-[22px]",
  },
  {
    eyebrow: "Get it on",
    label: "Google Play",
    icon: "/figmaAssets/google-play-6124997-1-2.png",
    iconClass: "w-[22px] h-[22px] object-cover",
  },
];

const quickLinks = [
  { label: "Home", href: "/" },
  { label: "About", href: "/#about" },
  { label: "Features", href: "/#features" },
  { label: "Terms & Conditions", href: "/terms-and-conditions" },
];

const socialIcons = [
  "/figmaAssets/tik-tok.png",
  "/figmaAssets/twiter-icon.png",
  "/figmaAssets/insta-icon.png",
];

const glassCardClass =
  "rounded-3xl overflow-hidden border border-white/10 bg-[linear-gradient(175deg,rgba(132,36,187,0.85)_0%,rgba(180,95,242,0.45)_100%)] shadow-[inset_-10px_10px_20px_#ffffff25,inset_0_1px_0_rgba(255,255,255,0.30),inset_1px_0_0_rgba(255,255,255,0.25)] backdrop-brightness-[110%] backdrop-blur-[12px]";

export const PrivacyPolicyPage = () => {
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");

  const filteredToc = tocSections.filter((sec) =>
    sec.label.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-[#000842] text-white font-['Manrope',sans-serif]">
      {/* Background Shapes & Blurs */}
      <img
        src="/figmaAssets/vector-1.svg"
        alt="Vector Background"
        className="absolute top-[-200px] left-[-300px] w-[1400px] opacity-40 pointer-events-none select-none"
      />
      <img
        src="/figmaAssets/rectangle-23469.svg"
        alt="Glow Shape"
        className="absolute top-[-300px] right-[-200px] w-[1000px] opacity-30 pointer-events-none select-none"
      />
      <div className="absolute left-[-200px] top-[400px] h-[500px] w-[500px] rounded-full bg-[#b45ff2] opacity-30 blur-[140px] pointer-events-none" />
      <div className="absolute right-[-150px] top-[1200px] h-[600px] w-[600px] rounded-full bg-[#8424bb] opacity-35 blur-[160px] pointer-events-none" />

      {/* Floating Stars */}
      <img
        src="/figmaAssets/star-12.svg"
        alt="Star"
        className="absolute top-[120px] left-[8%] w-[60px] opacity-70 pointer-events-none"
      />
      <img
        src="/figmaAssets/star-12.svg"
        alt="Star"
        className="absolute top-[280px] right-[10%] w-[45px] opacity-60 pointer-events-none"
      />
      <img
        src="/figmaAssets/star-12.svg"
        alt="Star"
        className="absolute top-[900px] left-[4%] w-[50px] opacity-50 pointer-events-none"
      />

      {/* HEADER NAVBAR */}
      <header className="relative z-50 w-full border-b border-white/10 bg-[#000842]/80 backdrop-blur-md">
        <div className="mx-auto flex min-h-[100px] w-full max-w-[1440px] items-center justify-between px-4 sm:px-8 lg:px-[100px] py-4">
          {/* Logo */}
          <a href="/" className="flex items-center gap-3 shrink-0" aria-label="Bar Huddle home">
            <img
              className="h-[60px] w-[61px] object-contain sm:h-[72px] sm:w-[73px]"
              alt="Bar Huddle Logo"
              src="/figmaAssets/bar-huddle---jpeg-1.png"
            />
            <span className="font-bold text-xl sm:text-2xl tracking-wide text-white">
              Bar<span className="text-[#b45ff2]">Huddle</span>
            </span>
          </a>

          {/* Desktop Nav */}
          <nav className="hidden md:block">
            <ul className="flex items-center gap-6 lg:gap-8">
              {navItems.map((item) => (
                <li key={item.label}>
                  <a
                    href={item.href}
                    className="text-sm font-medium text-white/90 transition-all hover:text-[#fdf88f] lg:text-base"
                  >
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          {/* Action button & Hamburger */}
          <div className="flex items-center gap-3">
            <a
              href="/"
              className="rounded-full bg-[#b45ff2] px-5 py-2.5 text-sm font-semibold text-white shadow-[0_0_15px_rgba(180,95,242,0.4)] transition-all hover:bg-[#a44ae8] hover:shadow-[0_0_25px_rgba(180,95,242,0.7)] sm:px-7 sm:py-3 sm:text-base"
            >
              Back to Home
            </a>

            {/* Mobile Hamburger */}
            <button
              id="mobile-menu-toggle"
              className="flex md:hidden h-10 w-10 items-center justify-center rounded-full border border-white/20 bg-white/10 text-white cursor-pointer"
              onClick={() => setMenuOpen(!menuOpen)}
              aria-label="Toggle menu"
            >
              {menuOpen ? (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              ) : (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="3" y1="6" x2="21" y2="6" />
                  <line x1="3" y1="12" x2="21" y2="12" />
                  <line x1="3" y1="18" x2="21" y2="18" />
                </svg>
              )}
            </button>
          </div>
        </div>

        {/* Mobile dropdown */}
        {menuOpen && (
          <div className="md:hidden border-t border-white/10 bg-[#000842]/95 px-6 py-4 backdrop-blur-lg">
            <nav className="flex flex-col gap-2">
              {navItems.map((item) => (
                <a
                  key={item.label}
                  href={item.href}
                  className="rounded-lg px-3 py-2 text-base font-normal text-white hover:bg-white/10"
                  onClick={() => setMenuOpen(false)}
                >
                  {item.label}
                </a>
              ))}
            </nav>
          </div>
        )}
      </header>

      {/* HERO SECTION */}
      <section className="relative z-10 mx-auto w-full max-w-[1440px] px-5 pt-12 pb-8 sm:px-8 lg:px-[100px] text-center lg:text-left">
        <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 pb-8 border-b border-white/10">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-[#b45ff2]/40 bg-[#b45ff2]/20 px-4 py-1.5 text-xs font-semibold uppercase tracking-wider text-[#fdf88f] backdrop-blur-md mb-4">
              <svg className="w-4 h-4 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
              </svg>
              Last updated: January 1, 2026
            </div>
            <h1 className="text-4xl sm:text-6xl lg:text-7xl font-bold leading-tight tracking-tight">
              Privacy <span className="text-[#b45ff2]">Policy</span>
            </h1>
            <p className="mt-4 max-w-2xl text-base sm:text-lg text-[#e7c7ff] leading-relaxed">
              Bar Huddle (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This policy details how we collect, safeguard, and use your personal information.
            </p>
          </div>

          {/* Quick Search */}
          <div className="w-full lg:w-[340px]">
            <label htmlFor="privacy-search" className="block text-xs font-semibold text-[#e7c7ff] mb-1.5 uppercase tracking-wide">
              Search Privacy Policy
            </label>
            <div className="relative">
              <input
                id="privacy-search"
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search topics (e.g. GDPR, CCPA, cookies...)"
                className="w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3 pl-10 text-sm text-white placeholder-white/50 focus:border-[#b45ff2] focus:bg-white/15 focus:outline-none backdrop-blur-md transition-all"
              />
              <svg
                className="absolute left-3 top-3.5 h-4 w-4 text-white/60"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery("")}
                  className="absolute right-3 top-3 text-xs text-white/60 hover:text-white"
                >
                  Clear
                </button>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* MAIN CONTENT AREA WITH SIDEBAR TOC */}
      <main className="relative z-10 mx-auto w-full max-w-[1440px] px-5 py-8 sm:px-8 lg:px-[100px]">
        <div className="grid grid-cols-1 lg:grid-cols-[300px_1fr] gap-10 items-start">
          
          {/* SIDEBAR TABLE OF CONTENTS */}
          <aside className="hidden lg:block sticky top-24 max-h-[calc(100vh-120px)] overflow-y-auto pr-2 rounded-2xl border border-white/10 bg-[#08083f]/60 p-5 backdrop-blur-md">
            <h2 className="text-sm font-bold uppercase tracking-wider text-[#fdf88f] mb-4 flex items-center gap-2">
              <svg className="w-4 h-4 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h7" />
              </svg>
              Table of Contents
            </h2>
            <nav className="flex flex-col gap-1 text-sm">
              {filteredToc.map((sec, idx) => (
                <a
                  key={sec.id}
                  href={`#${sec.id}`}
                  className="rounded-lg px-3 py-1.5 text-white/80 transition-all hover:bg-[#b45ff2]/20 hover:text-[#fdf88f] hover:translate-x-1"
                >
                  <span className="text-[#b45ff2] font-semibold mr-1.5">{idx + 1}.</span>
                  {sec.label}
                </a>
              ))}
              {filteredToc.length === 0 && (
                <div className="p-3 text-xs text-white/50 italic">No matching sections found</div>
              )}
            </nav>
          </aside>

          {/* MAIN LEGAL DOCUMENT CONTENT */}
          <div className="flex flex-col gap-8">
            
            {/* 1. INTRODUCTION */}
            <section id="intro" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  1
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Introduction &amp; Scope</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  Bar Huddle (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Bar Huddle.
                </p>
                <p>
                  This Privacy Policy applies to our website and app, and their associated subdomains (collectively, our &quot;Service&quot;), alongside our application, Bar Huddle. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms &amp; Conditions.
                </p>
              </div>
            </section>

            {/* 2. DEFINITIONS AND KEY TERMS */}
            <section id="definitions" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  2
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Definitions and Key Terms</h2>
              </div>
              <p className="text-white/90 mb-6 leading-relaxed">
                To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, they are strictly defined as:
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {definitions.map((def) => (
                  <div
                    key={def.term}
                    className="rounded-2xl border border-white/10 bg-[#000842]/60 p-4 transition-all hover:border-[#b45ff2]/50 hover:bg-[#000842]/80"
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <div className="p-1.5 rounded-lg bg-[#b45ff2]/20">
                        {def.icon}
                      </div>
                      <h3 className="font-bold text-lg text-[#fdf88f]">{def.term}</h3>
                    </div>
                    <p className="text-sm text-white/80 leading-relaxed">{def.desc}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* 3. WHAT INFORMATION DO WE COLLECT? */}
            <section id="info-collected" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  3
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">What Information Do We Collect?</h2>
              </div>
              <p className="text-white/90 mb-4 leading-relaxed">
                We collect information from you when you visit our website or app, register on our site, place an order, subscribe to our newsletter, respond to a survey, or fill out a form:
              </p>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
                {[
                  { title: "Name / Username", icon: "👤" },
                  { title: "Email Address", icon: "✉️" },
                  { title: "Age", icon: "🎂" },
                  { title: "Password", icon: "🔑" },
                ].map((item) => (
                  <div key={item.title} className="flex items-center gap-2.5 rounded-xl border border-white/10 bg-[#000842]/60 p-3">
                    <span className="text-xl">{item.icon}</span>
                    <span className="text-sm font-semibold text-white">{item.title}</span>
                  </div>
                ))}
              </div>

              <h3 className="font-bold text-lg text-[#fdf88f] mb-3">Optional Mobile Permissions</h3>
              <div className="space-y-3 text-sm text-white/90">
                <div className="rounded-xl border border-white/10 bg-[#000842]/50 p-4">
                  <div className="font-bold text-white mb-1">📍 Location (GPS)</div>
                  <div>Location data helps us build an accurate picture of your interests, which can be used to bring more targeted and relevant advertising to potential customers.</div>
                </div>
                <div className="rounded-xl border border-white/10 bg-[#000842]/50 p-4">
                  <div className="font-bold text-white mb-1">📷 Camera (pictures)</div>
                  <div>Granting camera permission allows you to upload pictures directly from the platform; you may safely deny camera permission on this platform.</div>
                </div>
                <div className="rounded-xl border border-white/10 bg-[#000842]/50 p-4">
                  <div className="font-bold text-white mb-1">🖼️ Photo gallery (pictures)</div>
                  <div>Granting photo gallery access allows you to upload pictures from your photo gallery; you may safely deny photo gallery access on this platform.</div>
                </div>
              </div>
            </section>

            {/* 4. THIRD PARTY END USER INFO */}
            <section id="third-party-end-user" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  4
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">End User Information From Third Parties</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                Bar Huddle collects End User Data necessary to provide the Bar Huddle Service to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with such information, we may also collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting those websites and adjusting your privacy settings.
              </p>
            </section>

            {/* 5. THIRD PARTY CUSTOMER INFO */}
            <section id="third-party-customer" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  5
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Customer Information From Third Parties</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We receive some information from third parties when you contact us. For example, when you submit your email address to express interest in becoming a Bar Huddle customer, we receive information from a third party that provides automated fraud-detection services to Bar Huddle. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting those websites and adjusting your privacy settings.
              </p>
            </section>

            {/* 6. SHARING INFORMATION */}
            <section id="sharing-info" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  6
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Do We Share the Information We Collect With Third Parties?</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  We may share the information we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we believe may interest you. We may also share it with our current and future affiliated companies and business partners, and, if we are involved in a merger, asset sale, or other business reorganization, we may share or transfer your personal and non-personal information to our successors in interest.
                </p>
                <p>
                  We may engage trusted third-party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and website/app, database storage and management, email management, marketing, credit card processing, customer service, and fulfilling orders for products and services you may purchase through the website/app. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
                </p>
                <p>
                  We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate your general location and other technical characteristics, such as connection speed, whether you have visited the website/app from a shared location, and the type of device used to visit it.
                </p>
                <div className="rounded-xl border border-amber-400/30 bg-amber-500/10 p-4 text-amber-200 text-sm">
                  We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties when we, in our sole discretion, believe it is necessary or appropriate to respond to claims or legal process (including subpoenas), to protect our rights and interests or those of a third party, to protect the safety of the public or any person, to prevent or stop illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules, and regulations.
                </div>
              </div>
            </section>

            {/* 7. COLLECTION SCOPE */}
            <section id="collection-scope" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  7
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Where and When Is Information Collected?</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                Bar Huddle collects personal information that you submit to us directly. We may also receive personal information about you from third parties, as described above.
              </p>
            </section>

            {/* 8. HOW WE USE INFORMATION */}
            <section id="use-info" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  8
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">How Do We Use the Information We Collect?</h2>
              </div>
              <p className="text-white/90 mb-4 leading-relaxed">
                Any information we collect from you may be used in one of the following ways:
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                {[
                  "To personalize your experience based on your individual needs.",
                  "To improve our website/app offerings and customer experience.",
                  "To respond effectively to your customer service requests and support.",
                  "To process transactions securely.",
                  "To administer a contest, promotion, survey, or site feature.",
                  "To send periodic email communications.",
                ].map((item, idx) => (
                  <div key={idx} className="flex items-start gap-3 rounded-xl border border-white/10 bg-[#000842]/50 p-3.5">
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#b45ff2] text-xs font-bold text-white">
                      ✓
                    </span>
                    <span className="text-white/90">{item}</span>
                  </div>
                ))}
              </div>
            </section>

            {/* 9. EMAIL USAGE */}
            <section id="email-usage" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  9
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">How Do We Use Your Email Address?</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  By submitting your email address on this website/app, you agree to receive emails from us. You may cancel your participation in any of these email lists at any time by clicking the opt-out link or other unsubscribe option included in the relevant email. We only send emails to people who have authorized us to contact them, either directly or through a third party, and we do not send unsolicited commercial emails.
                </p>
                <p>
                  By submitting your email address, you also agree to allow us to use it for customer audience targeting on platforms such as Facebook, where we display customized advertising to people who have opted in to receive communications from us. Email addresses submitted only through the order-processing page will be used solely to send you information and updates about your order.
                </p>
              </div>
            </section>

            {/* 10. RETENTION */}
            <section id="retention" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  10
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">How Long Do We Keep Your Information?</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We keep your information only for as long as we need it to provide the Bar Huddle Service to you and to fulfill the purposes described in this policy. This is also true for anyone we share your information with who carries out services on our behalf. When we no longer need to use your information, and there is no need for us to retain it to comply with our legal or regulatory obligations, we will either remove it from our systems or depersonalize it so that it can no longer identify you.
              </p>
            </section>

            {/* 11. PROTECTION */}
            <section id="protection" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  11
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">How Do We Protect Your Information?</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access it. We use a secure server, and all supplied sensitive or credit information is transmitted using Secure Socket Layer (SSL) technology and then encrypted into our payment gateway provider&apos;s database, accessible only to those authorized with special access rights who are required to keep the information confidential.
                </p>
                <div className="rounded-xl border border-[#fdf88f]/40 bg-[#fdf88f]/10 p-4 font-semibold text-[#fdf88f]">
                  After a transaction, your private information (credit card numbers, social security numbers, financial details, etc.) is never kept on file.
                </div>
                <p className="text-sm text-white/70 italic">
                  We cannot, however, guarantee the absolute security of any information you transmit to Bar Huddle, or that your information on the Service will never be accessed, disclosed, altered, or destroyed through a breach of our physical, technical, or managerial safeguards.
                </p>
              </div>
            </section>

            {/* 12. INTERNATIONAL TRANSFERS */}
            <section id="international-transfers" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  12
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Could My Information Be Transferred to Other Countries?</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                Bar Huddle is incorporated in the United States. Information collected through our website/app, through direct interactions with you, or from use of our help services may from time to time be transferred to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.
              </p>
            </section>

            {/* 13. SECURITY STANDARDS */}
            <section id="security-standards" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  13
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Is Information Collected Through Bar Huddle Secure?</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We take precautions to protect the security of your information and maintain physical, electronic, and managerial procedures to help safeguard it, prevent unauthorized access, and maintain data security. However, neither people nor security systems are foolproof, including encryption systems, and people can commit intentional crimes, make mistakes, or fail to follow policies. While we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standard used to measure our compliance with that duty.
              </p>
            </section>

            {/* 14. UPDATE OR CORRECT INFO */}
            <section id="update-correct" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  14
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Can I Update or Correct My Information?</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  The rights you have to request updates or corrections to information Bar Huddle collects depend on your relationship with Bar Huddle. Personnel may update or correct their information as described in our internal company employment policies.
                </p>
                <p>
                  Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You may contact us to (1) update or correct your personally identifiable information, (2) change your preferences regarding communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems by canceling your account.
                </p>
                <p className="text-sm text-white/80">
                  Because our systems must be backed up to protect information from inadvertent loss, a copy of your information may exist in a non-erasable form that is difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use will be updated, corrected, changed, or deleted as soon as technically practicable.
                </p>
              </div>
            </section>

            {/* 15. PERSONNEL */}
            <section id="personnel" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  15
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Personnel</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                If you are a Bar Huddle worker or applicant, we collect information you voluntarily provide to us. We use the information collected for human resources purposes, in order to administer benefits to workers and screen applicants. You may contact us to update, correct, or request a record of the information we hold relating to you.
              </p>
            </section>

            {/* 16. SALE OF BUSINESS */}
            <section id="business-sale" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  16
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Sale of Business</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We reserve the right to transfer information to a third party in the event of a sale, merger, or other transfer of all or substantially all of the assets of Bar Huddle or any of its corporate affiliates, provided that the third party agrees to adhere to the terms of this Privacy Policy.
              </p>
            </section>

            {/* 17. AFFILIATES */}
            <section id="affiliates" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  17
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Affiliates</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We may disclose information (including personal information) about you to our corporate affiliates. For purposes of this Privacy Policy, &quot;corporate affiliate&quot; means any person or entity that directly or indirectly controls, is controlled by, or is under common control with Bar Huddle, whether through ownership or otherwise.
              </p>
            </section>

            {/* 18. GOVERNING LAW */}
            <section id="governing-law" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  18
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Governing Law</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                This Privacy Policy is governed by the laws of the United States, without regard to its conflict-of-laws provisions. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy, except for individuals who may have rights to make claims under the Privacy Shield framework or the Swiss-U.S. framework.
              </p>
            </section>

            {/* 19. YOUR CONSENT */}
            <section id="user-consent" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  19
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Your Consent</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We have updated our Privacy Policy to provide you with complete transparency about what is collected when you visit our site and how that information is used. By using Bar Huddle, registering an account, or making a purchase, you consent to this Privacy Policy and agree to its terms.
              </p>
            </section>

            {/* 20. EXTERNAL LINKS */}
            <section id="external-links" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  20
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Links to Other Websites</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                This Privacy Policy applies only to the Services. The Services may contain links to other websites that are not operated or controlled by Bar Huddle. We are not responsible for the content, accuracy, or opinions expressed on such websites. Please note that when you follow a link from the Services to another website, this Privacy Policy no longer applies.
              </p>
            </section>

            {/* 21. COOKIES */}
            <section id="cookies" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  21
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Cookies</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                Bar Huddle uses &quot;cookies&quot; to identify the areas of our website or app that you have visited. A cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our website and app, although they are not essential to their use. We never place personally identifiable information in cookies.
              </p>
            </section>

            {/* 22. BLOCKING COOKIES */}
            <section id="blocking-cookies" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  22
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Blocking and Disabling Cookies</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                Wherever you are located, you may set your browser to block cookies and similar technologies, but doing so may block our essential cookies and prevent our website/app from functioning properly. Disabling a cookie does not delete the cookie from your browser; you will need to do this yourself from within your browser&apos;s settings menu.
              </p>
            </section>

            {/* 23. KIDS' PRIVACY */}
            <section id="kids-privacy" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  23
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Kids&apos; Privacy</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We do not knowingly address, or collect personally identifiable information from, anyone under the age of 13. If you are a parent or guardian and are aware that your child has provided us with personal data, please contact us. If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we will take steps to remove that information from our servers.
              </p>
            </section>

            {/* 24. POLICY CHANGES */}
            <section id="policy-changes" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  24
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Changes to Our Privacy Policy</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We may change our Service and policies, and we may need to make changes to this Privacy Policy so that it accurately reflects our Service and policies. Unless otherwise required by law, we will notify you before we make changes to this Privacy Policy and give you an opportunity to review them before they take effect. If you continue to use the Service after the updated Privacy Policy takes effect, you will be bound by it.
              </p>
            </section>

            {/* 25. THIRD-PARTY SERVICES */}
            <section id="third-party-services" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  25
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Third-Party Services</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We may display, include, or make available third-party content or provide links to third-party websites or services (&quot;Third-Party Services&quot;). You acknowledge and agree that Bar Huddle is not responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, or quality.
              </p>
            </section>

            {/* 26. TRACKING TECHNOLOGIES */}
            <section id="tracking-tech" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  26
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Tracking Technologies</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <div className="rounded-2xl border border-white/10 bg-[#000842]/60 p-4">
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Google Maps API</h3>
                  <p className="text-sm">
                    Google Maps API is a robust tool that can be used to create custom maps, searchable maps, check-in functions, live location data synchronization, route planning, and other similar features. It collects information held in accordance with its own Privacy Policy.
                  </p>
                </div>
                <div className="rounded-2xl border border-white/10 bg-[#000842]/60 p-4">
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Local Storage</h3>
                  <p className="text-sm">
                    Local storage (DOM storage) provides web apps with client-side persistent data storage, similar to cookies but with enhanced capacity and no data sent in HTTP request headers.
                  </p>
                </div>
                <div className="rounded-2xl border border-white/10 bg-[#000842]/60 p-4">
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Sessions</h3>
                  <p className="text-sm">
                    We use &quot;sessions&quot; to identify the areas of our platform that you have visited during your active browsing session.
                  </p>
                </div>
              </div>
            </section>

            {/* 27. GDPR COMPLIANCE */}
            <section id="gdpr-compliance" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  27
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">General Data Protection Regulation (GDPR)</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  If you are located in the European Economic Area (EEA), we collect and process your personal data in full compliance with GDPR principles. Bar Huddle applies GDPR controls as our baseline standard across all global operations.
                </p>
                <div className="rounded-2xl border border-[#b45ff2]/40 bg-[#b45ff2]/20 p-5">
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-2">Individual Data Subject&apos;s Rights</h3>
                  <p className="text-sm leading-relaxed mb-3">
                    Bar Huddle stores all conversation and personal data for up to six (6) years unless your account is deleted, in which case we dispose of all data in accordance with our Terms &amp; Conditions and this Privacy Policy within sixty (60) days.
                  </p>
                  <p className="text-sm leading-relaxed">
                    You have the right to access, update, retrieve, restrict, or remove your personal data at any time by contacting our support team.
                  </p>
                </div>
              </div>
            </section>

            {/* 28. CALIFORNIA RESIDENTS (CCPA) */}
            <section id="california-ccpa" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  28
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">California Residents (CCPA)</h2>
              </div>
              <p className="text-white/90 mb-4 leading-relaxed">
                Under the California Consumer Privacy Act (CCPA), California residents have specific privacy rights regarding their personal data:
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm mb-4">
                <div className="rounded-xl border border-white/10 bg-[#000842]/50 p-4">
                  <div className="font-bold text-[#fdf88f] mb-1">Right to Know &amp; Access</div>
                  <div>Request categories and specific pieces of personal information collected, used, or shared.</div>
                </div>
                <div className="rounded-xl border border-white/10 bg-[#000842]/50 p-4">
                  <div className="font-bold text-[#fdf88f] mb-1">Right to Equal Service</div>
                  <div>We will never discriminate against you for exercising your legal privacy rights.</div>
                </div>
                <div className="rounded-xl border border-white/10 bg-[#000842]/50 p-4">
                  <div className="font-bold text-[#fdf88f] mb-1">Right to Delete</div>
                  <div>Submit a request to close your account and delete your personal information.</div>
                </div>
                <div className="rounded-xl border border-white/10 bg-[#000842]/50 p-4">
                  <div className="font-bold text-[#fdf88f] mb-1">Right to Opt-Out</div>
                  <div>Request refraining from selling personal data. (Note: Bar Huddle does NOT sell user personal data).</div>
                </div>
              </div>

              <div className="rounded-xl border border-[#fdf88f]/40 bg-[#fdf88f]/10 p-4 font-semibold text-[#fdf88f] text-sm">
                We do not sell the personal information of our users.
              </div>
            </section>

            {/* 29. CalOPPA RIGHTS */}
            <section id="caloppa" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  29
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">CalOPPA Disclosures</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base mb-4">
                CalOPPA requires us to disclose personal information categories collected, sources, and third-party sharing. CalOPPA users hold full Rights to Know, Equal Service, Deletion, and Opt-Out as outlined above. If you make a request, we have one month to respond to you.
              </p>
            </section>

            {/* 30. CONTACT US */}
            <section id="contact-us" className="rounded-3xl border border-[#b45ff2]/40 bg-[linear-gradient(135deg,rgba(180,95,242,0.4)_0%,rgba(132,36,187,0.7)_100%)] p-6 sm:p-8 md:p-10 shadow-2xl backdrop-blur-xl">
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fdf88f] text-[#000842] font-bold text-lg shadow-md">
                  30
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Contact Us</h2>
              </div>
              <p className="text-white/90 mb-6 text-base">
                Please do not hesitate to contact us if you have any questions regarding this Privacy Policy.
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <a
                  href="mailto:support@barhuddle.com"
                  className="flex items-center gap-4 rounded-2xl border border-white/20 bg-white/10 p-5 transition-all hover:bg-white/20 hover:scale-[1.02]"
                >
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#b45ff2] text-white">
                    <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-wider text-[#e7c7ff] font-semibold">Via Email</div>
                    <div className="text-lg font-bold text-[#fdf88f]">support@barhuddle.com</div>
                  </div>
                </a>

                <a
                  href="https://barhuddle.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-4 rounded-2xl border border-white/20 bg-white/10 p-5 transition-all hover:bg-white/20 hover:scale-[1.02]"
                >
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#b45ff2] text-white">
                    <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m-9 9a9 9 0 019-9" />
                    </svg>
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-wider text-[#e7c7ff] font-semibold">Via Website</div>
                    <div className="text-lg font-bold text-[#fdf88f]">barhuddle.com</div>
                  </div>
                </a>
              </div>
            </section>

          </div>
        </div>
      </main>

      {/* FOOTER matching Landing Page & Terms Page */}
      <footer
        className="relative rounded-t-[80px] sm:rounded-t-[100px] mt-16 w-full overflow-hidden backdrop-blur-[25px]"
        style={{
          background: "linear-gradient(238.16deg, #B45FF2 19.57%, #8424BB 82.32%)",
        }}
      >
        <img
          className="absolute left-[29px] top-[5px] hidden h-[561px] w-[568px] lg:block opacity-20 pointer-events-none"
          alt="Bar Huddle Decoration"
          src="/figmaAssets/bar-huddle---jpeg-2.png"
        />
        <div className="relative z-10 mx-auto w-full max-w-[1440px] px-5 pb-10 pt-[100px] sm:px-8 lg:px-[86px] lg:pb-[60px] lg:pt-[130px]">
          <div className="grid grid-cols-1 gap-10 lg:grid-cols-[360px_133px_206px_336px] lg:justify-center">
            
            {/* Social Links */}
            <div className="flex flex-col items-start gap-5 lg:pt-20">
              <h3 className="font-semibold text-[22px] text-white">Social Links</h3>
              <div className="flex flex-wrap items-center gap-3 lg:gap-4">
                {socialIcons.map((src, index) => (
                  <img
                    key={`social-privacy-${index}`}
                    className="h-[35px] w-[63px] sm:h-[42px] sm:w-[76px] lg:h-[50px] lg:w-[50px]"
                    alt="Social icon"
                    src={src}
                  />
                ))}
              </div>
            </div>

            {/* Quick Links */}
            <nav className="flex flex-col items-start gap-5">
              <div className="font-semibold text-[22px] text-white">Quick Links</div>
              <div className="flex flex-col items-start gap-2.5">
                {quickLinks.map((link) => (
                  <a
                    key={link.label}
                    href={link.href}
                    className="text-base font-normal text-white hover:text-[#fdf88f] transition-colors"
                  >
                    {link.label}
                  </a>
                ))}
              </div>
            </nav>

            {/* Address */}
            <address className="flex flex-col items-start gap-5 not-italic">
              <div className="font-semibold text-[22px] text-white">Contact</div>
              <div className="flex flex-col items-start gap-2.5 text-base text-white">
                <div>support@barhuddle.com</div>
                <div>+1 (555) 123-4567</div>
                <div>29 Hillside Road Greenwich CT 06830</div>
              </div>
            </address>

            {/* App Store buttons */}
            <div className="flex flex-col items-start gap-5">
              <div className="font-semibold text-[22px] text-white">Get Bar Huddle</div>
              <p className="text-base text-white">
                Discover real-time nightlife, connect with people, and experience your city.
              </p>
              <div className="inline-flex flex-col items-start justify-center gap-4">
                {storeButtons.map((button) => (
                  <button
                    key={`footer-privacy-${button.label}`}
                    className="h-auto w-[180px] rounded-[364.1px] border border-solid border-[#e7c7ff] bg-[#8424bb] px-4 py-2 shadow-[0px_0px_8px_2px_#b45ff2] cursor-pointer hover:bg-[#731da6] transition-all"
                  >
                    <span className="flex items-center justify-center gap-2.5">
                      <img className={button.iconClass} alt={button.label} src={button.icon} />
                      <span className="inline-flex flex-col items-start justify-center gap-px">
                        <span className="text-xs font-medium text-white">{button.eyebrow}</span>
                        <span className="text-sm font-bold text-white">{button.label}</span>
                      </span>
                    </span>
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="mt-10">
            <img className="h-px w-full" alt="Divider" src="/figmaAssets/vector-2446.svg" />
            <div className="mt-8 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
              <div className="text-base font-medium text-white">
                © 2026 Bar Huddle App. All Rights Reserved.
              </div>
              <div className="flex flex-wrap items-center gap-6 sm:gap-8">
                <a href="/privacy-policy" className="text-base font-medium text-[#fdf88f] underline">
                  Privacy Policy
                </a>
                <a href="/terms-and-conditions" className="text-base font-medium text-white hover:text-[#fdf88f] transition-colors">
                  Terms &amp; Conditions
                </a>
                <a href="/child-safety-policy" className="text-base font-medium text-white hover:text-[#fdf88f] transition-colors">
                  Child Safety Policy
                </a>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};
