"use client";

import React, { useState } from "react";

const navItems = [
  { label: "Home", href: "/" },
  { label: "How it works", href: "/#how-it-works" },
  { label: "Features", href: "/#features" },
  { label: "About", href: "/#about" },
  { label: "Contact", href: "/#contact" },
];

const definitions = [
  {
    term: "Cookie",
    desc: "Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
  },
  {
    term: "Company",
    desc: 'When these terms mention "Company," "we," "us," or "our," it refers to Bar Huddle Cooperation, (29 Hillside Road Greenwich CT 06830), that is responsible for your information under this Terms & Conditions.',
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5m0 0v-5a2 2 0 012-2h2a2 2 0 012 2v5m-6 0h6" />
      </svg>
    ),
  },
  {
    term: "Country",
    desc: "Where Bar Huddle or the owners/founders of Bar Huddle are based, in this case is United States.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 002 2h1.5a2.5 2.5 0 002.5-2.5V11a2 2 0 012-2h1.055" />
      </svg>
    ),
  },
  {
    term: "Device",
    desc: "Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Bar Huddle and use the services.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 18h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
      </svg>
    ),
  },
  {
    term: "Service",
    desc: "Refers to the service provided by Bar Huddle as described in the relative terms (if available) and on this platform.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
      </svg>
    ),
  },
  {
    term: "Third-party service",
    desc: "Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
      </svg>
    ),
  },
  {
    term: "You",
    desc: "A person or entity that is registered with Bar Huddle to use the Services.",
    icon: (
      <svg className="w-5 h-5 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
      </svg>
    ),
  },
];

const tocSections = [
  { id: "general-terms", label: "General Terms" },
  { id: "license", label: "License" },
  { id: "definitions", label: "Definitions & Key Terms" },
  { id: "restrictions", label: "Restrictions" },
  { id: "refund-policy", label: "Return & Refund Policy" },
  { id: "suggestions", label: "Your Suggestions" },
  { id: "consent", label: "Your Consent" },
  { id: "third-party-links", label: "Links to Other Websites" },
  { id: "cookies", label: "Cookies" },
  { id: "changes-to-terms", label: "Changes To Terms" },
  { id: "modifications", label: "Modifications to Website/App" },
  { id: "updates", label: "Updates to Website/App" },
  { id: "third-party-services", label: "Third-Party Services" },
  { id: "termination", label: "Term and Termination" },
  { id: "copyright", label: "Copyright Infringement" },
  { id: "indemnification", label: "Indemnification" },
  { id: "warranties", label: "No Warranties" },
  { id: "liability", label: "Limitation of Liability" },
  { id: "severability", label: "Severability & Waiver" },
  { id: "amendments", label: "Amendments & Entire Agreement" },
  { id: "intellectual-property", label: "Intellectual Property" },
  { id: "arbitration", label: "Dispute Resolution & Arbitration" },
  { id: "submissions-promotions", label: "Submissions & Promotions" },
  { id: "errors-misc", label: "Typographical Errors & Misc" },
  { id: "disclaimer", label: "Disclaimer" },
  { id: "contact-us", label: "Contact Us" },
];

const storeButtons = [
  {
    eyebrow: "Available on the",
    label: "App Store",
    icon: "/figmaAssets/logos-apple-app-store.svg",
    iconClass: "w-[22px] h-[22px]",
  },
  {
    eyebrow: "Get it on",
    label: "Google Play",
    icon: "/figmaAssets/google-play-6124997-1-2.png",
    iconClass: "w-[22px] h-[22px] object-cover",
  },
];

const quickLinks = [
  { label: "Home", href: "/" },
  { label: "About", href: "/#about" },
  { label: "Features", href: "/#features" },
  { label: "Contact", href: "/#contact" },
];

const socialIcons = [
  "/figmaAssets/tik-tok.png",
  "/figmaAssets/twiter-icon.png",
  "/figmaAssets/insta-icon.png",
];

const glassCardClass =
  "rounded-3xl overflow-hidden border border-white/10 bg-[linear-gradient(175deg,rgba(132,36,187,0.85)_0%,rgba(180,95,242,0.45)_100%)] shadow-[inset_-10px_10px_20px_#ffffff25,inset_0_1px_0_rgba(255,255,255,0.30),inset_1px_0_0_rgba(255,255,255,0.25)] backdrop-brightness-[110%] backdrop-blur-[12px]";

export const TermsPage = () => {
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");

  const filteredToc = tocSections.filter((sec) =>
    sec.label.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-[#000842] text-white font-['Manrope',sans-serif]">
      {/* Background Shapes & Blurs matching Landing Page */}
      <img
        src="/figmaAssets/vector-1.svg"
        alt="Vector Background"
        className="absolute top-[-200px] left-[-300px] w-[1400px] opacity-40 pointer-events-none select-none"
      />
      <img
        src="/figmaAssets/rectangle-23469.svg"
        alt="Glow Shape"
        className="absolute top-[-300px] right-[-200px] w-[1000px] opacity-30 pointer-events-none select-none"
      />
      <div className="absolute left-[-200px] top-[400px] h-[500px] w-[500px] rounded-full bg-[#b45ff2] opacity-30 blur-[140px] pointer-events-none" />
      <div className="absolute right-[-150px] top-[1200px] h-[600px] w-[600px] rounded-full bg-[#8424bb] opacity-35 blur-[160px] pointer-events-none" />

      {/* Floating Stars */}
      <img
        src="/figmaAssets/star-12.svg"
        alt="Star"
        className="absolute top-[120px] left-[8%] w-[60px] opacity-70 pointer-events-none"
      />
      <img
        src="/figmaAssets/star-12.svg"
        alt="Star"
        className="absolute top-[280px] right-[10%] w-[45px] opacity-60 pointer-events-none"
      />
      <img
        src="/figmaAssets/star-12.svg"
        alt="Star"
        className="absolute top-[900px] left-[4%] w-[50px] opacity-50 pointer-events-none"
      />

      {/* HEADER NAVBAR */}
      <header className="relative z-50 w-full border-b border-white/10 bg-[#000842]/80 backdrop-blur-md">
        <div className="mx-auto flex min-h-[100px] w-full max-w-[1440px] items-center justify-between px-4 sm:px-8 lg:px-[100px] py-4">
          {/* Logo */}
          <a href="/" className="flex items-center gap-3 shrink-0" aria-label="Bar Huddle home">
            <img
              className="h-[60px] w-[61px] object-contain sm:h-[72px] sm:w-[73px]"
              alt="Bar Huddle Logo"
              src="/figmaAssets/bar-huddle---jpeg-1.png"
            />
            <span className="font-bold text-xl sm:text-2xl tracking-wide text-white">
              Bar<span className="text-[#b45ff2]">Huddle</span>
            </span>
          </a>

          {/* Desktop Nav */}
          <nav className="hidden md:block">
            <ul className="flex items-center gap-6 lg:gap-8">
              {navItems.map((item) => (
                <li key={item.label}>
                  <a
                    href={item.href}
                    className="text-sm font-medium text-white/90 transition-all hover:text-[#fdf88f] lg:text-base"
                  >
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          {/* Action button & Hamburger */}
          <div className="flex items-center gap-3">
            <a
              href="/"
              className="rounded-full bg-[#b45ff2] px-5 py-2.5 text-sm font-semibold text-white shadow-[0_0_15px_rgba(180,95,242,0.4)] transition-all hover:bg-[#a44ae8] hover:shadow-[0_0_25px_rgba(180,95,242,0.7)] sm:px-7 sm:py-3 sm:text-base"
            >
              Back to Home
            </a>

            {/* Mobile Hamburger */}
            <button
              id="mobile-menu-toggle"
              className="flex md:hidden h-10 w-10 items-center justify-center rounded-full border border-white/20 bg-white/10 text-white cursor-pointer"
              onClick={() => setMenuOpen(!menuOpen)}
              aria-label="Toggle menu"
            >
              {menuOpen ? (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              ) : (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <line x1="3" y1="6" x2="21" y2="6" />
                  <line x1="3" y1="12" x2="21" y2="12" />
                  <line x1="3" y1="18" x2="21" y2="18" />
                </svg>
              )}
            </button>
          </div>
        </div>

        {/* Mobile dropdown */}
        {menuOpen && (
          <div className="md:hidden border-t border-white/10 bg-[#000842]/95 px-6 py-4 backdrop-blur-lg">
            <nav className="flex flex-col gap-2">
              {navItems.map((item) => (
                <a
                  key={item.label}
                  href={item.href}
                  className="rounded-lg px-3 py-2 text-base font-normal text-white hover:bg-white/10"
                  onClick={() => setMenuOpen(false)}
                >
                  {item.label}
                </a>
              ))}
            </nav>
          </div>
        )}
      </header>

      {/* HERO SECTION */}
      <section className="relative z-10 mx-auto w-full max-w-[1440px] px-5 pt-12 pb-8 sm:px-8 lg:px-[100px] text-center lg:text-left">
        <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 pb-8 border-b border-white/10">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-[#b45ff2]/40 bg-[#b45ff2]/20 px-4 py-1.5 text-xs font-semibold uppercase tracking-wider text-[#fdf88f] backdrop-blur-md mb-4">
              <svg className="w-4 h-4 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              Updated at January 1st, 2026
            </div>
            <h1 className="text-4xl sm:text-6xl lg:text-7xl font-bold leading-tight tracking-tight">
              Terms & <span className="text-[#b45ff2]">Conditions</span>
            </h1>
            <p className="mt-4 max-w-2xl text-base sm:text-lg text-[#e7c7ff] leading-relaxed">
              Welcome to Bar Huddle. Please review our legal agreement outlined below carefully before using our platform, app, or website services.
            </p>
          </div>

          {/* Quick Search */}
          <div className="w-full lg:w-[340px]">
            <label htmlFor="terms-search" className="block text-xs font-semibold text-[#e7c7ff] mb-1.5 uppercase tracking-wide">
              Search Terms & Conditions
            </label>
            <div className="relative">
              <input
                id="terms-search"
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search topics (e.g. refund, cookies...)"
                className="w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3 pl-10 text-sm text-white placeholder-white/50 focus:border-[#b45ff2] focus:bg-white/15 focus:outline-none backdrop-blur-md transition-all"
              />
              <svg
                className="absolute left-3 top-3.5 h-4 w-4 text-white/60"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery("")}
                  className="absolute right-3 top-3 text-xs text-white/60 hover:text-white"
                >
                  Clear
                </button>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* MAIN CONTENT AREA WITH SIDEBAR TOC */}
      <main className="relative z-10 mx-auto w-full max-w-[1440px] px-5 py-8 sm:px-8 lg:px-[100px]">
        <div className="grid grid-cols-1 lg:grid-cols-[300px_1fr] gap-10 items-start">
          
          {/* SIDEBAR TABLE OF CONTENTS */}
          <aside className="hidden lg:block sticky top-24 max-h-[calc(100vh-120px)] overflow-y-auto pr-2 rounded-2xl border border-white/10 bg-[#08083f]/60 p-5 backdrop-blur-md">
            <h2 className="text-sm font-bold uppercase tracking-wider text-[#fdf88f] mb-4 flex items-center gap-2">
              <svg className="w-4 h-4 text-[#fdf88f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h7" />
              </svg>
              Table of Contents
            </h2>
            <nav className="flex flex-col gap-1 text-sm">
              {filteredToc.map((sec, idx) => (
                <a
                  key={sec.id}
                  href={`#${sec.id}`}
                  className="rounded-lg px-3 py-1.5 text-white/80 transition-all hover:bg-[#b45ff2]/20 hover:text-[#fdf88f] hover:translate-x-1"
                >
                  <span className="text-[#b45ff2] font-semibold mr-1.5">{idx + 1}.</span>
                  {sec.label}
                </a>
              ))}
              {filteredToc.length === 0 && (
                <div className="p-3 text-xs text-white/50 italic">No matching sections found</div>
              )}
            </nav>
          </aside>

          {/* MAIN LEGAL DOCUMENT CONTENT */}
          <div className="flex flex-col gap-8">
            
            {/* 1. GENERAL TERMS */}
            <section id="general-terms" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  1
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">General Terms</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  By accessing and placing an order with Bar Huddle, you confirm that you are in agreement with and bound by the terms of service contained in the Terms &amp; Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Bar Huddle.
                </p>
                <div className="rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-200 leading-relaxed">
                  Under no circumstances shall Bar Huddle team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Bar Huddle team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
                </div>
                <p>
                  Bar Huddle will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
                </p>
              </div>
            </section>

            {/* 2. LICENSE */}
            <section id="license" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  2
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">License</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  Bar Huddle grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website/app strictly in accordance with the terms of this Agreement.
                </p>
                <p>
                  These Terms &amp; Conditions are a contract between you and Bar Huddle (referred to in these Terms &amp; Conditions as &quot;Bar Huddle&quot;, &quot;us&quot;, &quot;we&quot; or &quot;our&quot;), the provider of the Bar Huddle website and the services accessible from the Bar Huddle website (which are collectively referred to in these Terms &amp; Conditions as the &quot;Bar Huddle Service&quot;).
                </p>
                <p>
                  You are agreeing to be bound by these Terms &amp; Conditions. If you do not agree to these Terms &amp; Conditions, please do not use the Bar Huddle Service. In these Terms &amp; Conditions, &quot;you&quot; refers both to you as an individual and to the entity you represent. If you violate any of these Terms &amp; Conditions, we reserve the right to cancel your account or block access to your account without notice.
                </p>
              </div>
            </section>

            {/* 3. DEFINITIONS AND KEY TERMS */}
            <section id="definitions" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  3
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Definitions and Key Terms</h2>
              </div>
              <p className="text-white/90 mb-6 leading-relaxed">
                To help explain things as clearly as possible in this Terms &amp; Conditions, every time any of these terms are referenced, they are strictly defined as:
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {definitions.map((def) => (
                  <div
                    key={def.term}
                    className="rounded-2xl border border-white/10 bg-[#000842]/60 p-4 transition-all hover:border-[#b45ff2]/50 hover:bg-[#000842]/80"
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <div className="p-1.5 rounded-lg bg-[#b45ff2]/20">
                        {def.icon}
                      </div>
                      <h3 className="font-bold text-lg text-[#fdf88f]">{def.term}</h3>
                    </div>
                    <p className="text-sm text-white/80 leading-relaxed">{def.desc}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* 4. RESTRICTIONS */}
            <section id="restrictions" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  4
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Restrictions</h2>
              </div>
              <p className="text-white/90 mb-4">You agree not to, and you will not permit others to:</p>
              <ul className="space-y-3 text-white/90">
                <li className="flex items-start gap-3 rounded-xl border border-white/5 bg-white/5 p-3.5">
                  <svg className="w-5 h-5 text-[#b45ff2] shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
                  </svg>
                  <span>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website/app or make the platform available to any third party.</span>
                </li>
                <li className="flex items-start gap-3 rounded-xl border border-white/5 bg-white/5 p-3.5">
                  <svg className="w-5 h-5 text-[#b45ff2] shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
                  </svg>
                  <span>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website/app.</span>
                </li>
                <li className="flex items-start gap-3 rounded-xl border border-white/5 bg-white/5 p-3.5">
                  <svg className="w-5 h-5 text-[#b45ff2] shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" />
                  </svg>
                  <span>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Bar Huddle or its affiliates, partners, suppliers or the licensors of the website/app.</span>
                </li>
              </ul>
            </section>

            {/* 5. RETURN AND REFUND POLICY */}
            <section id="refund-policy" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  5
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Return and Refund Policy</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  Thanks for shopping at Bar Huddle. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.
                </p>
                <p>
                  As with any shopping experience, there are terms and conditions that apply to transactions at Bar Huddle. The main thing to remember is that by placing an order or making a purchase at Bar Huddle, you agree to the terms along with Bar Huddle’s Privacy Policy.
                </p>
                <div className="rounded-xl border border-[#b45ff2]/40 bg-[#b45ff2]/15 p-4 text-[#fdf88f]">
                  If, for any reason, You are not completely satisfied with any good or service that we provide, don&apos;t hesitate to contact us and we will discuss any of the issues you are going through with our product.
                </div>
              </div>
            </section>

            {/* 6. YOUR SUGGESTIONS */}
            <section id="suggestions" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  6
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Your Suggestions</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  Any feedback, comments, ideas, improvements or suggestions (collectively, &quot;Suggestions&quot;) provided by you to Bar Huddle with respect to the website/app shall remain the sole and exclusive property of Bar Huddle.
                </p>
                <p>
                  Bar Huddle shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
                </p>
              </div>
            </section>

            {/* 7. YOUR CONSENT */}
            <section id="consent" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  7
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Your Consent</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                We&apos;ve updated our Terms &amp; Conditions to provide you with complete transparency into what is being set when you visit our site and how it&apos;s being used. By using our website/app, registering an account, or making a purchase, you hereby consent to our Terms &amp; Conditions.
              </p>
            </section>

            {/* 8. LINKS TO OTHER WEBSITES */}
            <section id="third-party-links" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  8
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Links to Other Websites</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                This Terms &amp; Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by Bar Huddle. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms &amp; Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
              </p>
            </section>

            {/* 9. COOKIES */}
            <section id="cookies" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  9
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Cookies</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                Bar Huddle uses &quot;Cookies&quot; to identify the areas of our website/app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website/app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website/app as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website/app correctly or at all. We never place Personally Identifiable Information in Cookies.
              </p>
            </section>

            {/* 10. CHANGES TO OUR TERMS & CONDITIONS */}
            <section id="changes-to-terms" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  10
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Changes To Our Terms &amp; Conditions</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  You acknowledge and agree that Bar Huddle may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Bar Huddle’s sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Bar Huddle when you stop using the Service. You acknowledge and agree that if Bar Huddle disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.
                </p>
                <p>
                  If we decide to change our Terms &amp; Conditions, we will post those changes on this page, and/or update the Terms &amp; Conditions modification date below.
                </p>
              </div>
            </section>

            {/* 11. MODIFICATIONS TO OUR WEBSITE/APP */}
            <section id="modifications" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  11
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Modifications to Our Website/App</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                Bar Huddle reserves the right to modify, suspend or discontinue, temporarily or permanently, the website/app or any service to which it connects, with or without notice and without liability to you.
              </p>
            </section>

            {/* 12. UPDATES TO OUR WEBSITE/APP */}
            <section id="updates" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  12
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Updates to Our Website/App</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  Bar Huddle may from time to time provide enhancements or improvements to the features/ functionality of the website/app, which may include patches, bug fixes, updates, upgrades and other modifications (&quot;Updates&quot;).
                </p>
                <p>
                  Updates may modify or delete certain features and/or functionalities of the website/app. You agree that Bar Huddle has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website/app to you.
                </p>
                <p>
                  You further agree that all Updates will be (i) deemed to constitute an integral part of the website/app, and (ii) subject to the terms and conditions of this Agreement.
                </p>
              </div>
            </section>

            {/* 13. THIRD-PARTY SERVICES */}
            <section id="third-party-services" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  13
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Third-Party Services</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (&quot;Third-Party Services&quot;).
                </p>
                <p>
                  You acknowledge and agree that Bar Huddle shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Bar Huddle does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.
                </p>
                <p>
                  Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties&apos; terms and conditions.
                </p>
              </div>
            </section>

            {/* 14. TERM AND TERMINATION */}
            <section id="termination" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  14
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Term and Termination</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>This Agreement shall remain in effect until terminated by you or Bar Huddle.</p>
                <p>Bar Huddle may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.</p>
                <p>This Agreement will terminate immediately, without prior notice from Bar Huddle, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website/app and all copies thereof from your computer.</p>
                <p>Upon termination of this Agreement, you shall cease all use of the website/app and delete all copies of the website/app from your computer.</p>
                <p>Termination of this Agreement will not limit any of Bar Huddle&apos;s rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.</p>
              </div>
            </section>

            {/* 15. COPYRIGHT INFRINGEMENT NOTICE */}
            <section id="copyright" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  15
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Copyright Infringement Notice</h2>
              </div>
              <p className="text-white/90 mb-4 leading-relaxed">
                If you are a copyright owner or such owner’s agent and believe any material on our website/app constitutes an infringement on your copyright, please contact us setting forth the following information:
              </p>
              <div className="grid grid-cols-1 gap-3 text-sm text-white/90">
                <div className="flex items-start gap-2.5 rounded-xl border border-white/10 bg-[#000842]/50 p-3">
                  <span className="font-bold text-[#fdf88f]">(a)</span>
                  <span>A physical or electronic signature of the copyright owner or a person authorized to act on his behalf;</span>
                </div>
                <div className="flex items-start gap-2.5 rounded-xl border border-white/10 bg-[#000842]/50 p-3">
                  <span className="font-bold text-[#fdf88f]">(b)</span>
                  <span>Identification of the material that is claimed to be infringing;</span>
                </div>
                <div className="flex items-start gap-2.5 rounded-xl border border-white/10 bg-[#000842]/50 p-3">
                  <span className="font-bold text-[#fdf88f]">(c)</span>
                  <span>Your contact information, including your address, telephone number, and an email;</span>
                </div>
                <div className="flex items-start gap-2.5 rounded-xl border border-white/10 bg-[#000842]/50 p-3">
                  <span className="font-bold text-[#fdf88f]">(d)</span>
                  <span>A statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and</span>
                </div>
                <div className="flex items-start gap-2.5 rounded-xl border border-white/10 bg-[#000842]/50 p-3">
                  <span className="font-bold text-[#fdf88f]">(e)</span>
                  <span>A statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.</span>
                </div>
              </div>
            </section>

            {/* 16. INDEMNIFICATION */}
            <section id="indemnification" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  16
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Indemnification</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                You agree to indemnify and hold Bar Huddle and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys&apos; fees, due to or arising out of your: (a) use of the website/app; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.
              </p>
            </section>

            {/* 17. NO WARRANTIES */}
            <section id="warranties" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  17
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">No Warranties</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  The website/app is provided to you &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Bar Huddle, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website/app, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Bar Huddle provides no warranty or undertaking, and makes no representation of any kind that the website/app will meet your requirements, achieve any intended results, be compatible or work with any other software, website/apps, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.
                </p>
                <p>
                  Without limiting the foregoing, neither Bar Huddle nor any Bar Huddle&apos;s provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website/app, or the information, content, and materials or products included thereon; (ii) that the website/app will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website/app; or (iv) that the website/app, its servers, the content, or e-mails sent from or on behalf of Bar Huddle are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.
                </p>
                <p className="text-sm text-white/70 italic">
                  Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.
                </p>
              </div>
            </section>

            {/* 18. LIMITATION OF LIABILITY */}
            <section id="liability" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  18
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Limitation of Liability</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  Notwithstanding any damages that you might incur, the entire liability of Bar Huddle and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website/app.
                </p>
                <p>
                  To the maximum extent permitted by applicable law, in no event shall Bar Huddle or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website/app, third-party software and/or third-party hardware used with the website/app, or otherwise in connection with any provision of this Agreement), even if Bar Huddle or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.
                </p>
                <p className="text-sm text-white/70 italic">
                  Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
                </p>
              </div>
            </section>

            {/* 19. SEVERABILITY AND WAIVER */}
            <section id="severability" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  19
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Severability &amp; Waiver</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.
                </p>
                <p>
                  This Agreement, together with the Privacy Policy and any other legal notices published by Bar Huddle on the Services, shall constitute the entire agreement between you and Bar Huddle concerning the Services.
                </p>
                <div className="rounded-xl border border-[#fdf88f]/40 bg-[#fdf88f]/10 p-4 font-semibold text-[#fdf88f]">
                  YOU AND BAR HUDDLE AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
                </div>
                <p>
                  Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party&apos;s ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.
                </p>
              </div>
            </section>

            {/* 20. AMENDMENTS & ENTIRE AGREEMENT */}
            <section id="amendments" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  20
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Amendments &amp; Entire Agreement</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>
                  Bar Huddle reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days&apos; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
                </p>
                <p>
                  By continuing to access or use our website/app after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Bar Huddle.
                </p>
                <p>
                  The Agreement constitutes the entire agreement between you and Bar Huddle regarding your use of the website/app and supersedes all prior and contemporaneous written or oral agreements between you and Bar Huddle.
                </p>
              </div>
            </section>

            {/* 21. INTELLECTUAL PROPERTY */}
            <section id="intellectual-property" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  21
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Intellectual Property</h2>
              </div>
              <p className="text-white/90 leading-relaxed text-base">
                The website/app and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by Bar Huddle, its licensors or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of Bar Huddle, unless and except as is expressly provided in these Terms &amp; Conditions. Any unauthorized use of the material is prohibited.
              </p>
            </section>

            {/* 22. DISPUTE RESOLUTION & BINDING ARBITRATION */}
            <section id="arbitration" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  22
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Dispute Resolution &amp; Binding Arbitration</h2>
              </div>
              <div className="space-y-5 text-white/90 leading-relaxed text-base">
                <div>
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Agreement to Arbitrate</h3>
                  <p>
                    This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR BAR HUDDLE’S INTELLECTUAL PROPERTY RIGHTS. The term “dispute” means any dispute, action, or other controversy between you and Bar Huddle concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. “Dispute” will be given the broadest possible meaning allowable under law.
                  </p>
                </div>

                <div className="rounded-2xl border border-white/10 bg-[#000842]/70 p-5">
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-2">Notice of Dispute</h3>
                  <p className="mb-3">
                    In the event of a dispute, you or Bar Huddle must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to:
                  </p>
                  <a
                    href="mailto:support@barhuddle.com"
                    className="inline-flex items-center gap-2 rounded-xl bg-[#b45ff2]/30 px-4 py-2 text-[#fdf88f] font-semibold hover:bg-[#b45ff2]/50 transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                    support@barhuddle.com
                  </a>
                  <p className="mt-3 text-sm text-white/80">
                    Bar Huddle will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and Bar Huddle will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or Bar Huddle may commence arbitration.
                  </p>
                </div>

                <div>
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Binding Arbitration</h3>
                  <p>
                    If you and Bar Huddle don’t resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party’s rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.
                  </p>
                </div>
              </div>
            </section>

            {/* 23. SUBMISSIONS & PROMOTIONS */}
            <section id="submissions-promotions" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  23
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Submissions &amp; Promotions</h2>
              </div>
              <div className="space-y-5 text-white/90 leading-relaxed text-base">
                <div>
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Submissions and Privacy</h3>
                  <p>
                    In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of Bar Huddle without any compensation or credit to you whatsoever. Bar Huddle and its affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Promotions</h3>
                  <p>
                    Bar Huddle may, from time to time, include contests, promotions, sweepstakes, or other activities (“Promotions”) that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules.
                  </p>
                </div>
              </div>
            </section>

            {/* 24. TYPOGRAPHICAL ERRORS & MISCELLANEOUS */}
            <section id="errors-misc" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  24
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Typographical Errors &amp; Miscellaneous</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <div>
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Typographical Errors</h3>
                  <p>
                    In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold text-lg text-[#fdf88f] mb-1">Miscellaneous</h3>
                  <p>
                    If for any reason a court of competent jurisdiction finds any provision or portion of these Terms &amp; Conditions to be unenforceable, the remainder of these Terms &amp; Conditions will continue in full force and effect. Any waiver of any provision of these Terms &amp; Conditions will be effective only if in writing and signed by an authorized representative of Bar Huddle. Bar Huddle will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. Bar Huddle operates and controls the Bar Huddle Service from its offices in United States. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the Bar Huddle Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms &amp; Conditions (which include and incorporate the Bar Huddle Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and Bar Huddle concerning its subject matter, and cannot be changed or modified by you.
                  </p>
                </div>
              </div>
            </section>

            {/* 25. DISCLAIMER */}
            <section id="disclaimer" className={`${glassCardClass} p-6 sm:p-8 md:p-10`}>
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#b45ff2] text-white font-bold text-lg shadow-md">
                  25
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Disclaimer</h2>
              </div>
              <div className="space-y-4 text-white/90 leading-relaxed text-base">
                <p>Bar Huddle is not responsible for any content, code or any other imprecision.</p>
                <p className="font-semibold text-[#fdf88f]">Bar Huddle does not provide warranties or guarantees.</p>
                <p>
                  In no event shall Bar Huddle be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.
                </p>
                <p>
                  The Bar Huddle Service and its contents are provided &quot;as is&quot; and &quot;as available&quot; without any warranty or representations of any kind, whether express or implied. Bar Huddle is a distributor and not a publisher of the content supplied by third parties; as such, Bar Huddle exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Bar Huddle Service. Without limiting the foregoing, Bar Huddle specifically disclaims all warranties and representations in any content transmitted on or in connection with the Bar Huddle Service or on sites that may appear as links on the Bar Huddle Service, or in the products provided as a part of, or otherwise in connection with, the Bar Huddle Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Bar Huddle or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Bar Huddle does not warrant that the Bar Huddle Service will be uninterrupted, uncorrupted, timely, or error-free.
                </p>
              </div>
            </section>

            {/* 26. CONTACT US */}
            <section id="contact-us" className="rounded-3xl border border-[#b45ff2]/40 bg-[linear-gradient(135deg,rgba(180,95,242,0.4)_0%,rgba(132,36,187,0.7)_100%)] p-6 sm:p-8 md:p-10 shadow-2xl backdrop-blur-xl">
              <div className="flex items-center gap-3 mb-4">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fdf88f] text-[#000842] font-bold text-lg shadow-md">
                  26
                </span>
                <h2 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">Contact Us</h2>
              </div>
              <p className="text-white/90 mb-6 text-base">
                Don&apos;t hesitate to contact us if you have any questions regarding these Terms &amp; Conditions.
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <a
                  href="mailto:support@barhuddle.com"
                  className="flex items-center gap-4 rounded-2xl border border-white/20 bg-white/10 p-5 transition-all hover:bg-white/20 hover:scale-[1.02]"
                >
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#b45ff2] text-white">
                    <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-wider text-[#e7c7ff] font-semibold">Via Email</div>
                    <div className="text-lg font-bold text-[#fdf88f]">support@barhuddle.com</div>
                  </div>
                </a>

                <a
                  href="https://barhuddle.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-4 rounded-2xl border border-white/20 bg-white/10 p-5 transition-all hover:bg-white/20 hover:scale-[1.02]"
                >
                  <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#b45ff2] text-white">
                    <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
                    </svg>
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-wider text-[#e7c7ff] font-semibold">Via Website</div>
                    <div className="text-lg font-bold text-[#fdf88f]">barhuddle.com</div>
                  </div>
                </a>
              </div>
            </section>

          </div>
        </div>
      </main>

      {/* FOOTER matching Landing Page */}
      <footer
        className="relative rounded-t-[80px] sm:rounded-t-[100px] mt-16 w-full overflow-hidden backdrop-blur-[25px]"
        style={{
          background: "linear-gradient(238.16deg, #B45FF2 19.57%, #8424BB 82.32%)",
        }}
      >
        <img
          className="absolute left-[29px] top-[5px] hidden h-[561px] w-[568px] lg:block opacity-20 pointer-events-none"
          alt="Bar Huddle Decoration"
          src="/figmaAssets/bar-huddle---jpeg-2.png"
        />
        <div className="relative z-10 mx-auto w-full max-w-[1440px] px-5 pb-10 pt-[100px] sm:px-8 lg:px-[86px] lg:pb-[60px] lg:pt-[130px]">
          <div className="grid grid-cols-1 gap-10 lg:grid-cols-[360px_133px_206px_336px] lg:justify-center">
            
            {/* Social Links */}
            <div className="flex flex-col items-start gap-5 lg:pt-20">
              <h3 className="font-semibold text-[22px] text-white">Social Links</h3>
              <div className="flex flex-wrap items-center gap-3 lg:gap-4">
                {socialIcons.map((src, index) => (
                  <img
                    key={`social-${index}`}
                    className="h-[35px] w-[63px] sm:h-[42px] sm:w-[76px] lg:h-[50px] lg:w-[50px]"
                    alt="Social icon"
                    src={src}
                  />
                ))}
              </div>
            </div>

            {/* Quick Links */}
            <nav className="flex flex-col items-start gap-5">
              <div className="font-semibold text-[22px] text-white">Quick Links</div>
              <div className="flex flex-col items-start gap-2.5">
                {quickLinks.map((link) => (
                  <a
                    key={link.label}
                    href={link.href}
                    className="text-base font-normal text-white hover:text-[#fdf88f] transition-colors"
                  >
                    {link.label}
                  </a>
                ))}
              </div>
            </nav>

            {/* Address */}
            <address className="flex flex-col items-start gap-5 not-italic">
              <div className="font-semibold text-[22px] text-white">Contact</div>
              <div className="flex flex-col items-start gap-2.5 text-base text-white">
                <div>support@barhuddle.com</div>
                <div>+1 (555) 123-4567</div>
                <div>29 Hillside Road Greenwich CT 06830</div>
              </div>
            </address>

            {/* App Store buttons */}
            <div className="flex flex-col items-start gap-5">
              <div className="font-semibold text-[22px] text-white">Get Bar Huddle</div>
              <p className="text-base text-white">
                Discover real-time nightlife, connect with people, and experience your city.
              </p>
              <div className="inline-flex flex-col items-start justify-center gap-4">
                {storeButtons.map((button) => (
                  <button
                    key={`footer-terms-${button.label}`}
                    className="h-auto w-[180px] rounded-[364.1px] border border-solid border-[#e7c7ff] bg-[#8424bb] px-4 py-2 shadow-[0px_0px_8px_2px_#b45ff2] cursor-pointer hover:bg-[#731da6] transition-all"
                  >
                    <span className="flex items-center justify-center gap-2.5">
                      <img className={button.iconClass} alt={button.label} src={button.icon} />
                      <span className="inline-flex flex-col items-start justify-center gap-px">
                        <span className="text-xs font-medium text-white">{button.eyebrow}</span>
                        <span className="text-sm font-bold text-white">{button.label}</span>
                      </span>
                    </span>
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="mt-10">
            <img className="h-px w-full" alt="Divider" src="/figmaAssets/vector-2446.svg" />
            <div className="mt-8 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
              <div className="text-base font-medium text-white">
                © 2026 Bar Huddle App. All Rights Reserved.
              </div>
              <div className="flex items-center gap-8">
                <a href="/privacy-policy" className="text-base font-medium text-white hover:text-[#fdf88f] transition-colors">
                  Privacy Policy
                </a>
                <a href="/terms-and-conditions" className="text-base font-medium text-[#fdf88f] underline">
                  Terms &amp; Conditions
                </a>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};
